#pragma once

/*
 * tideflow_ffi.h — C API of the TideFlow storage core (Rust).
 * Generated by cbindgen from rust/tideflow-ffi/src/lib.rs. DO NOT EDIT.
 * Regenerate with: cbindgen --config rust/cbindgen.toml --output tideflow_ffi.h rust/tideflow-ffi
 */

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

// Size in bytes of a row position (`handler::ref_length`).
#define TF_POSITION_LEN 16

typedef enum {
  TF_OK = 0,
  TF_ERR_IO = 1,
  TF_ERR_CORRUPT = 2,
  TF_ERR_FULL = 3,
  TF_ERR_NOT_FOUND = 4,
  TF_ERR_INVALID_ARG = 5,
  TF_ERR_OOM = 6,
  TF_ERR_READONLY = 7,
  // A Rust panic was caught at the boundary.
  TF_ERR_INTERNAL = 8,
  // The operation is declared but not implemented yet.
  TF_ERR_UNSUPPORTED = 9,
} TFStatus;

// Column type codes used in `TFTableConfig::column_types` and `TFValue::kind`.
typedef enum {
  TF_COL_TIMESTAMP = 0,
  TF_COL_INT64 = 1,
  TF_COL_FLOAT64 = 2,
  TF_COL_FLOAT32 = 3,
  TF_COL_BOOL = 4,
  TF_COL_VARCHAR = 5,
  TF_COL_TAG = 6,
  TF_COL_DECIMAL = 7,
} TFColumnType;

// Opaque scan handle.
typedef struct TideFlowScan TideFlowScan;

// Opaque table handle.
typedef struct TideFlowTable TideFlowTable;

// Table configuration. String options may be NULL to select defaults.
typedef struct {
  // Overrides the table directory (DATA DIRECTORY); NULL = use `name`.
  const char *data_dir;
  const char *chunk_interval;
  const char *retention_period;
  const char *compression;
  // 0 = default (3).
  uint8_t compression_level;
  const char *hot_threshold;
  // 0 = default (64 MiB).
  uint64_t memtable_size_bytes;
  uint32_t ts_column_index;
  uint32_t column_count;
  // May be NULL; otherwise `column_count` NUL-terminated names.
  const char *const *column_names;
  // `column_count` `TFColumnType` codes.
  const uint8_t *column_types;
} TFTableConfig;

typedef struct {
  const char *ptr;
  uint32_t len;
} TFStr;

typedef union {
  // Microseconds since the Unix epoch (TF_COL_TIMESTAMP).
  int64_t ts_us;
  int64_t int_val;
  double float_val;
  float float32_val;
  // 0 or 1. A byte rather than `bool` so any value written by C is valid.
  uint8_t bool_val;
  // TF_COL_VARCHAR, TF_COL_TAG and TF_COL_DECIMAL (canonical string form).
  TFStr str_val;
} TFValueData;

typedef struct {
  // A `TFColumnType` code; must match the column's declared type.
  uint8_t kind;
  bool is_null;
  TFValueData data;
} TFValue;

typedef struct {
  uint32_t col_count;
  TFValue *values;
} TFRow;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Creates the on-disk structure of a new table.
//
// # Safety
// `name` must be a NUL-terminated path; `config` must be valid.
TFStatus tideflow_table_create(const char *name, const TFTableConfig *config);

// Opens a table (running crash recovery). On success `*out_table` receives a
// handle to release with `tideflow_table_close`.
//
// # Safety
// As `tideflow_table_create`; `out_table` must be writable.
TFStatus tideflow_table_open(const char *name,
                             const TFTableConfig *config,
                             TideFlowTable **out_table);

// Releases a table handle. Pending WAL data is flushed to the OS.
//
// # Safety
// `table` must come from `tideflow_table_open` and not be used afterwards.
// Every scan opened on it should be closed first.
TFStatus tideflow_table_close(TideFlowTable *table);

// # Safety
// `name` must be a NUL-terminated path.
TFStatus tideflow_table_drop(const char *name);

// # Safety
// `from` and `to` must be NUL-terminated paths.
TFStatus tideflow_table_rename(const char *from, const char *to);

// Appends one row (WAL + MemTable). Durable after `tideflow_sync_wal(.., true)`.
//
// # Safety
// `row` must point to `col_count` valid values matching the table's columns.
TFStatus tideflow_write_row(TideFlowTable *table, const TFRow *row);

// Statement-end hook: flushes buffered WAL entries to the OS and, when
// `durable`, fsyncs them.
//
// # Safety
// `table` must be a valid handle.
TFStatus tideflow_sync_wal(TideFlowTable *table, bool durable);

// Seals the MemTable into chunk files.
//
// # Safety
// `table` must be a valid handle.
TFStatus tideflow_flush(TideFlowTable *table);

// Removes all rows (TRUNCATE TABLE / DELETE without WHERE).
//
// # Safety
// `table` must be a valid handle.
TFStatus tideflow_truncate(TideFlowTable *table);

// Opens an unordered full-table scan (forward only).
//
// # Safety
// `table` must be a valid handle; `out_scan` writable.
TFStatus tideflow_scan_open(TideFlowTable *table, TideFlowScan **out_scan);

// Opens a scan of rows with `ts_start_us <= ts <= ts_end_us` whose TAG columns
// equal the given values, ordered by timestamp. Supports `tideflow_scan_prev`.
//
// # Safety
// `tag_col_indices` and `tag_values` must hold `tag_count` elements each.
TFStatus tideflow_range_scan_open(TideFlowTable *table,
                                  int64_t ts_start_us,
                                  int64_t ts_end_us,
                                  const uint32_t *tag_col_indices,
                                  const TFValue *tag_values,
                                  uint32_t tag_count,
                                  TideFlowScan **out_scan);

// Advances the scan. At the end, `*out_eof` is set and `out_row` emptied.
//
// # Safety
// `scan` must be valid; `out_row` and `out_eof` writable.
TFStatus tideflow_scan_next(TideFlowScan *scan, TFRow *out_row, bool *out_eof);

// Steps backwards (range scans only). Before the first row, `*out_bof` is set.
//
// # Safety
// As `tideflow_scan_next`.
TFStatus tideflow_scan_prev(TideFlowScan *scan, TFRow *out_row, bool *out_bof);

// Positions a range scan after its last row (for `index_last`).
//
// # Safety
// `scan` must be valid.
TFStatus tideflow_scan_seek_end(TideFlowScan *scan);

// Writes the `TF_POSITION_LEN`-byte position of the row last returned.
//
// # Safety
// `out_pos` must have room for `TF_POSITION_LEN` bytes.
TFStatus tideflow_scan_position(TideFlowScan *scan, uint8_t *out_pos);

// Re-reads the row at `pos` into `out_row` (handler `rnd_pos`). The scan's
// current row becomes that row.
//
// # Safety
// `pos` must point to `TF_POSITION_LEN` readable bytes.
TFStatus tideflow_scan_fetch(TideFlowScan *scan, const uint8_t *pos, TFRow *out_row);

// # Safety
// `scan` must come from a `*_scan_open` call and not be used afterwards.
TFStatus tideflow_scan_close(TideFlowScan *scan);

// Merges chunks in a time range. Not implemented yet: returns `TF_ERR_UNSUPPORTED`.
//
// # Safety
// `table` must be a valid handle.
TFStatus tideflow_compact(TideFlowTable *table, int64_t ts_start_us, int64_t ts_end_us);

// Deletes chunks entirely older than RETENTION_PERIOD.
//
// # Safety
// `table` must be a valid handle.
TFStatus tideflow_apply_retention(TideFlowTable *table);

// Verifies the CRC32 of every chunk. `*out_bad_chunks` receives the number of
// damaged chunks; when non-zero, `tideflow_last_error` describes them.
//
// # Safety
// `table` must be valid; `out_bad_chunks` writable.
TFStatus tideflow_check(TideFlowTable *table, uint32_t *out_bad_chunks);

// Any out pointer may be NULL if the caller is not interested.
//
// # Safety
// `table` must be valid; non-NULL out pointers writable.
TFStatus tideflow_table_stats(TideFlowTable *table,
                              uint64_t *out_row_count,
                              uint64_t *out_data_bytes,
                              uint64_t *out_compressed_bytes,
                              uint32_t *out_chunk_count);

// Optimizer estimate of rows with `ts_start_us <= ts <= ts_end_us`.
//
// # Safety
// `table` must be valid; `out_rows` writable.
TFStatus tideflow_estimate_rows(TideFlowTable *table,
                                int64_t ts_start_us,
                                int64_t ts_end_us,
                                uint64_t *out_rows);

// Message of the last error raised on the calling thread, or NULL. The
// caller owns the result and must release it with `tideflow_free_str`.
char *tideflow_last_error(void);

// Releases a string allocated by this library. NULL is ignored.
//
// # Safety
// `ptr` must be NULL or a pointer returned by this library, freed only once.
void tideflow_free_str(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
