#pragma once

/*
 * moosedb_ffi.h — C API of the MooseDB storage core (Rust).
 * Generated by cbindgen from rust/moosedb-ffi/src/lib.rs. DO NOT EDIT.
 * Regenerate with: cbindgen --config rust/cbindgen.toml --output moosedb_ffi.h rust/moosedb-ffi
 */

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

// Size in bytes of a row position (`handler::ref_length`).
#define TF_POSITION_LEN 16

typedef enum {
  TF_OK = 0,
  TF_ERR_IO = 1,
  TF_ERR_CORRUPT = 2,
  TF_ERR_FULL = 3,
  TF_ERR_NOT_FOUND = 4,
  TF_ERR_INVALID_ARG = 5,
  TF_ERR_OOM = 6,
  TF_ERR_READONLY = 7,
  // A Rust panic was caught at the boundary.
  TF_ERR_INTERNAL = 8,
  // The operation or feature is not available.
  TF_ERR_UNSUPPORTED = 9,
} TFStatus;

// Column type codes used in `TFTableConfig::column_types` and `TFValue::kind`.
typedef enum {
  TF_COL_TIMESTAMP = 0,
  TF_COL_INT64 = 1,
  TF_COL_FLOAT64 = 2,
  TF_COL_FLOAT32 = 3,
  TF_COL_BOOL = 4,
  TF_COL_VARCHAR = 5,
  TF_COL_TAG = 6,
  TF_COL_DECIMAL = 7,
} TFColumnType;

// Opaque statement batch (see `moosedb_batch_begin`). Used by one thread.
typedef struct MooseDBBatch MooseDBBatch;

// Opaque diagnostics handle.
typedef struct MooseDBInfo MooseDBInfo;

// Opaque scan handle.
typedef struct MooseDBScan MooseDBScan;

// Opaque list of the series of a table.
typedef struct MooseDBSeriesList MooseDBSeriesList;

// Opaque snapshot handle: resolves row positions (`rnd_pos`).
typedef struct MooseDBSnapshot MooseDBSnapshot;

// Opaque table handle.
typedef struct MooseDBTable MooseDBTable;

// Process-wide tunables (the `moosedb_*` system variables).
typedef struct {
  uint64_t retention_check_interval_secs;
  uint32_t compaction_trigger_chunks;
  double bloom_filter_false_positive_rate;
  uint64_t chunk_cache_bytes;
  uint32_t max_open_chunks;
} TFGlobalSettings;

// Fetches an encryption key from the server. `version == 0` asks for the
// latest version. Writes the version used to `*out_version` and the 32-byte
// key to `out_key`. Returns 0 on success.
typedef int32_t (*TFKeyCallback)(uint32_t key_id,
                                 uint32_t version,
                                 uint32_t *out_version,
                                 uint8_t *out_key);

// Table configuration. String options may be NULL to select defaults.
typedef struct {
  // Overrides the table directory (DATA DIRECTORY); NULL = use `name`.
  const char *data_dir;
  const char *chunk_interval;
  const char *retention_period;
  const char *compression;
  // 0 = default (3).
  uint8_t compression_level;
  const char *hot_threshold;
  // 0 = default (64 MiB).
  uint64_t memtable_size_bytes;
  uint32_t ts_column_index;
  uint32_t column_count;
  // May be NULL; otherwise `column_count` NUL-terminated names.
  const char *const *column_names;
  // `column_count` `TFColumnType` codes.
  const uint8_t *column_types;
  // Key id for encryption at rest; 0 = not encrypted.
  uint32_t encryption_key_id;
} TFTableConfig;

typedef struct {
  const char *ptr;
  uint32_t len;
} TFStr;

typedef union {
  // Microseconds since the Unix epoch (TF_COL_TIMESTAMP).
  int64_t ts_us;
  int64_t int_val;
  double float_val;
  float float32_val;
  // 0 or 1. A byte rather than `bool` so any value written by C is valid.
  uint8_t bool_val;
  // TF_COL_VARCHAR, TF_COL_TAG and TF_COL_DECIMAL (canonical string form).
  TFStr str_val;
} TFValueData;

typedef struct {
  // A `TFColumnType` code; must match the column's declared type.
  uint8_t kind;
  bool is_null;
  TFValueData data;
} TFValue;

typedef struct {
  uint32_t col_count;
  TFValue *values;
} TFRow;

// Table-level diagnostics (INFORMATION_SCHEMA.MOOSEDB_TABLES). Strings are
// owned by the `MooseDBInfo` handle.
typedef struct {
  bool is_open;
  bool encrypted;
  uint64_t row_count;
  uint64_t pending_rows;
  uint64_t series_count;
  uint64_t data_bytes;
  uint64_t compressed_bytes;
  uint32_t chunk_count;
  uint32_t hot_chunks;
  uint32_t warm_chunks;
  uint32_t cold_chunks;
  uint32_t compacting_chunks;
  uint32_t expired_chunks;
  const char *chunk_interval;
  const char *retention_period;
  const char *compression;
} TFTableInfo;

// One chunk (INFORMATION_SCHEMA.MOOSEDB_CHUNKS).
typedef struct {
  uint64_t chunk_id;
  int64_t ts_min_us;
  int64_t ts_max_us;
  uint64_t rows;
  uint32_t series;
  uint64_t data_bytes;
  uint64_t compressed_bytes;
  int64_t sealed_at_us;
  bool encrypted;
  // "HOT", "WARM", "COLD", "COMPACTING" or "EXPIRED".
  const char *status;
  // "NONE", "LZ4" or "ZSTD".
  const char *compression;
  const char *file_name;
} TFChunkInfo;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Applies the `moosedb_*` system variables. Safe to call at any time.
//
// # Safety
// `s` must point to a valid `TFGlobalSettings`.
TFStatus moosedb_set_globals(const TFGlobalSettings *s);

// Installs (or, with NULL, removes) the encryption key provider.
TFStatus moosedb_set_key_callback(TFKeyCallback cb);

// Starts the background maintenance pool (retention, compaction).
TFStatus moosedb_maintenance_start(uint32_t threads);

// Stops the background maintenance pool, waiting for running jobs.
TFStatus moosedb_maintenance_stop(void);

// Creates the on-disk structure of a new table.
//
// # Safety
// `name` must be a NUL-terminated path; `config` must be valid.
TFStatus moosedb_table_create(const char *name, const TFTableConfig *config);

// Opens a table (running crash recovery) or attaches to the instance already
// open in this process. Release the handle with `moosedb_table_close`.
//
// # Safety
// As `moosedb_table_create`; `out_table` must be writable.
TFStatus moosedb_table_open(const char *name,
                            const TFTableConfig *config,
                            MooseDBTable **out_table);

// Handle to the table at `path` if it is open in this process
// (`TF_ERR_NOT_FOUND` otherwise). Release with `moosedb_table_close`.
//
// # Safety
// `path` must be NUL-terminated; `out_table` writable.
TFStatus moosedb_table_lookup(const char *path, MooseDBTable **out_table);

// Releases a table handle; pending WAL data is flushed to the OS. The table
// itself closes when its last handle (and background job) is gone.
//
// # Safety
// `table` must come from `moosedb_table_open`/`_lookup` and not be used afterwards.
TFStatus moosedb_table_close(MooseDBTable *table);

// # Safety
// `name` must be a NUL-terminated path.
TFStatus moosedb_table_drop(const char *name);

// # Safety
// `from` and `to` must be NUL-terminated paths.
TFStatus moosedb_table_rename(const char *from, const char *to);

// Appends one row (WAL + MemTable). Durable after `moosedb_sync_wal(.., true)`.
//
// # Safety
// `row` must point to `col_count` valid values matching the table's columns.
TFStatus moosedb_write_row(MooseDBTable *table, const TFRow *row);

// Starts a statement batch. Rows written with `moosedb_batch_write` are
// invisible to every reader until `moosedb_batch_commit`, which publishes
// them all at once; a crash before the commit loses all of them, after a
// synced commit none. Any number of batches (and `moosedb_write_row` calls)
// may be open at the same time. Memory use is bounded: large batches spill
// to disk. The handle must end in `moosedb_batch_commit` or
// `moosedb_batch_abort`, which release it.
//
// # Safety
// `table` must be a valid handle; `out_batch` writable.
TFStatus moosedb_batch_begin(MooseDBTable *table, MooseDBBatch **out_batch);

// Adds one row to the batch (same value convention as `moosedb_write_row`).
// On error the row is not part of the batch; the batch stays usable.
//
// # Safety
// `batch` must be a live batch handle; `row` as in `moosedb_write_row`.
TFStatus moosedb_batch_write(MooseDBBatch *batch, const TFRow *row);

// Publishes every row of the batch at once and releases the handle (also on
// error: the handle is invalid afterwards). With `sync` the commit is durable
// when this returns.
//
// # Safety
// `batch` must come from `moosedb_batch_begin` and not be used afterwards.
TFStatus moosedb_batch_commit(MooseDBBatch *batch, bool sync);

// Discards the batch (none of its rows ever becomes visible) and releases the
// handle. NULL is ignored.
//
// # Safety
// `batch` must come from `moosedb_batch_begin` and not be used afterwards.
TFStatus moosedb_batch_abort(MooseDBBatch *batch);

// Statement-end hook: flushes buffered WAL entries to the OS and, when
// `durable`, fsyncs them.
//
// # Safety
// `table` must be a valid handle.
TFStatus moosedb_sync_wal(MooseDBTable *table, bool durable);

// Seals the MemTable into chunk files.
//
// # Safety
// `table` must be a valid handle.
TFStatus moosedb_flush(MooseDBTable *table);

// Removes all rows (TRUNCATE TABLE / DELETE without WHERE).
//
// # Safety
// `table` must be a valid handle.
TFStatus moosedb_truncate(MooseDBTable *table);

// Opens an unordered full-table scan (forward only).
//
// # Safety
// `table` must be a valid handle; `out_scan` writable.
TFStatus moosedb_scan_open(MooseDBTable *table, MooseDBScan **out_scan);

// Opens a scan of rows with `ts_start_us <= ts <= ts_end_us` whose TAG columns
// equal the given values, ordered by timestamp. Supports `moosedb_scan_prev`.
//
// # Safety
// `tag_col_indices` and `tag_values` must hold `tag_count` elements each.
TFStatus moosedb_range_scan_open(MooseDBTable *table,
                                 int64_t ts_start_us,
                                 int64_t ts_end_us,
                                 const uint32_t *tag_col_indices,
                                 const TFValue *tag_values,
                                 uint32_t tag_count,
                                 MooseDBScan **out_scan);

// General scan: timestamp range, optional series restriction
// (`series_count < 0` = all series), unordered or timestamp-ordered.
//
// # Safety
// `series_ids` must hold `series_count` elements when `series_count > 0`.
TFStatus moosedb_scan_open_filtered(MooseDBTable *table,
                                    int64_t ts_start_us,
                                    int64_t ts_end_us,
                                    const uint64_t *series_ids,
                                    int64_t series_count,
                                    bool sorted,
                                    MooseDBScan **out_scan);

// Advances the scan. At the end, `*out_eof` is set and `out_row` emptied.
//
// # Safety
// `scan` must be valid; `out_row` and `out_eof` writable.
TFStatus moosedb_scan_next(MooseDBScan *scan, TFRow *out_row, bool *out_eof);

// Steps backwards (sorted scans only). Before the first row, `*out_bof` is set.
//
// # Safety
// As `moosedb_scan_next`.
TFStatus moosedb_scan_prev(MooseDBScan *scan, TFRow *out_row, bool *out_bof);

// Positions a sorted scan after its last row (for `index_last`).
//
// # Safety
// `scan` must be valid.
TFStatus moosedb_scan_seek_end(MooseDBScan *scan);

// Writes the `TF_POSITION_LEN`-byte position of the row last returned.
//
// # Safety
// `out_pos` must have room for `TF_POSITION_LEN` bytes.
TFStatus moosedb_scan_position(MooseDBScan *scan, uint8_t *out_pos);

// Returns a handle on the snapshot the scan reads, which resolves the
// positions of its rows even after the scan is closed.
//
// # Safety
// `scan` must be valid; `out_snapshot` writable.
TFStatus moosedb_scan_snapshot(MooseDBScan *scan, MooseDBSnapshot **out_snapshot);

// # Safety
// `scan` must come from a `*_scan_open*` call and not be used afterwards.
TFStatus moosedb_scan_close(MooseDBScan *scan);

// Identifies the table contents the snapshot shows: equal versions mean
// identical snapshots.
//
// # Safety
// `snapshot` must be valid.
uint64_t moosedb_snapshot_version(const MooseDBSnapshot *snapshot);

// Re-reads the row at `pos` (handler `rnd_pos`). `TF_ERR_NOT_FOUND` if the
// snapshot does not cover that position.
//
// # Safety
// `pos` must point to `TF_POSITION_LEN` readable bytes; `out_row` writable.
TFStatus moosedb_snapshot_fetch(MooseDBSnapshot *snapshot, const uint8_t *pos, TFRow *out_row);

// # Safety
// `snapshot` must come from `moosedb_scan_snapshot` and not be used afterwards.
TFStatus moosedb_snapshot_close(MooseDBSnapshot *snapshot);

// Lists every series of the table (for TAG predicate pushdown).
//
// # Safety
// `table` must be valid; `out_list` writable.
TFStatus moosedb_series_list(MooseDBTable *table, MooseDBSeriesList **out_list);

// Number of series in the list.
//
// # Safety
// `list` must be valid.
uint64_t moosedb_series_list_len(const MooseDBSeriesList *list);

// Series `index`: its id and its TAG values (in table TAG-column order).
//
// # Safety
// `list` must be valid; `out_id`, `out_tags` writable.
TFStatus moosedb_series_list_get(MooseDBSeriesList *list,
                                 uint64_t index,
                                 uint64_t *out_id,
                                 TFRow *out_tags);

// # Safety
// `list` must come from `moosedb_series_list` and not be used afterwards.
TFStatus moosedb_series_list_close(MooseDBSeriesList *list);

// Merges the chunks of every time bucket overlapping `[ts_start_us,
// ts_end_us]` and re-encodes cold chunks with the cold codec.
//
// # Safety
// `table` must be a valid handle.
TFStatus moosedb_compact(MooseDBTable *table, int64_t ts_start_us, int64_t ts_end_us);

// Deletes chunks entirely older than RETENTION_PERIOD.
//
// # Safety
// `table` must be a valid handle.
TFStatus moosedb_apply_retention(MooseDBTable *table);

// Verifies the CRC32 of every chunk. `*out_bad_chunks` receives the number of
// damaged chunks; when non-zero, `moosedb_last_error` describes them.
//
// # Safety
// `table` must be valid; `out_bad_chunks` writable.
TFStatus moosedb_check(MooseDBTable *table, uint32_t *out_bad_chunks);

// Any out pointer may be NULL if the caller is not interested.
//
// # Safety
// `table` must be valid; non-NULL out pointers writable.
TFStatus moosedb_table_stats(MooseDBTable *table,
                             uint64_t *out_row_count,
                             uint64_t *out_data_bytes,
                             uint64_t *out_compressed_bytes,
                             uint32_t *out_chunk_count);

// Optimizer estimate of rows with `ts_start_us <= ts <= ts_end_us`.
//
// # Safety
// `table` must be valid; `out_rows` writable.
TFStatus moosedb_estimate_rows(MooseDBTable *table,
                               int64_t ts_start_us,
                               int64_t ts_end_us,
                               uint64_t *out_rows);

// Describes the table stored at `path` (open or not) for diagnostics.
//
// # Safety
// `path` must be NUL-terminated; `out_info` writable.
TFStatus moosedb_inspect(const char *path, MooseDBInfo **out_info);

// # Safety
// `info` must be valid. The result lives as long as `info`.
const TFTableInfo *moosedb_info_table(const MooseDBInfo *info);

// # Safety
// `info` must be valid.
uint32_t moosedb_info_chunk_count(const MooseDBInfo *info);

// Chunk `index`, or NULL when out of range. The result lives as long as `info`.
//
// # Safety
// `info` must be valid.
const TFChunkInfo *moosedb_info_chunk(const MooseDBInfo *info, uint32_t index);

// # Safety
// `info` must come from `moosedb_inspect` and not be used afterwards.
void moosedb_info_close(MooseDBInfo *info);

// Message of the last error raised on the calling thread, or NULL. The
// caller owns the result and must release it with `moosedb_free_str`.
char *moosedb_last_error(void);

// Releases a string allocated by this library. NULL is ignored.
//
// # Safety
// `ptr` must be NULL or a pointer returned by this library, freed only once.
void moosedb_free_str(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
